sonar.projectKey=ferrummalleator
sonar.organization=ferrummalleator
sonar.host.url=https://sonarcloud.io

# Coverage
sonar.cs.vscoveragexml.reportsPaths=**/coverage.cobertura.xml
sonar.coverage.exclusions=**/*Tests*.cs,**/tests/**,**/samples/**,**/.github/**

# Exclusões reais
sonar.exclusions=**/bin/**,**/obj/**,**/samples/**,**/examples/**,**/.github/**
