<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-FerrumMalleator.Nuntium.Samples-bfdd7a25-8ce4-4b29-87b6-29fa8b9bf0cb</UserSecretsId>
		<SonarQubeExclude>true</SonarQubeExclude>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.6" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\FerrumMalleator.Nuntium.Persistence.EntityFramework\FerrumMalleator.Nuntium.Persistence.EntityFramework.csproj" />
		<ProjectReference Include="..\..\src\FerrumMalleator.Nuntium\FerrumMalleator.Nuntium.csproj" />
	</ItemGroup>
</Project>
