<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>FerrumMalleator.Nuntium.Persistence.EntityFramework</PackageId>
		<Version>$(Version)</Version>
		<Description>Entity Framework persistence provider for FerrumMalleator.Nuntium.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/tmoreirafreitas/FerrumMalleator.Nuntium</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ProjectReference Include="..\FerrumMalleator.Nuntium\FerrumMalleator.Nuntium.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<PackageReference Include="FerrumMalleator.Nuntium" Version="0.1.0" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="FerrumMalleator.Nuntium.Tests" />
	</ItemGroup>
</Project>
