name: Publish NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # =========================
      # Restore
      # =========================

      - name: Restore Nuntium
        run: |
          dotnet restore src/FerrumMalleator.Nuntium/FerrumMalleator.Nuntium.csproj

      - name: Restore EF Package
        run: |
          dotnet restore src/FerrumMalleator.Nuntium.Persistence.EntityFramework/FerrumMalleator.Nuntium.Persistence.EntityFramework.csproj

      # =========================
      # Build
      # =========================

      - name: Build Nuntium
        run: |
          dotnet build src/FerrumMalleator.Nuntium/FerrumMalleator.Nuntium.csproj \
            -c Release \
            --no-restore

      - name: Build EF Package
        run: |
          dotnet build src/FerrumMalleator.Nuntium.Persistence.EntityFramework/FerrumMalleator.Nuntium.Persistence.EntityFramework.csproj \
            -c Release \
            --no-restore

      # =========================
      # Pack
      # =========================

      - name: Pack Nuntium
        run: |
          dotnet pack src/FerrumMalleator.Nuntium/FerrumMalleator.Nuntium.csproj \
            -c Release \
            --no-build \
            -p:Version=$VERSION

      - name: Pack EF Package
        run: |
          dotnet pack src/FerrumMalleator.Nuntium.Persistence.EntityFramework/FerrumMalleator.Nuntium.Persistence.EntityFramework.csproj \
            -c Release \
            --no-build \
            -p:Version=$VERSION

      # =========================
      # Publish
      # =========================

      - name: Publish core package
        run: |
          dotnet nuget push "src/**/FerrumMalleator.Nuntium.$VERSION.nupkg" \
            --skip-duplicate \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json

      - name: Publish EF package
        run: |
          dotnet nuget push "src/**/FerrumMalleator.Nuntium.Persistence.EntityFramework.$VERSION.nupkg" \
            --skip-duplicate \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json